---
# Make Installation Playbook
# Cross-distribution make installation with package name mapping
# Supports: Debian/Ubuntu, RHEL/Fedora/CentOS, Arch, SUSE, Alpine

- name: Install Make across distributions
  hosts: localhost
  connection: local
  gather_facts: yes
  become: yes
  
  vars:
    # Package name mappings for different distributions
    make_packages:
      # Debian family (Ubuntu, Debian, Pop!_OS, etc.)
      Debian: make
      Ubuntu: make
      "Pop!_OS": make
      "Linux Mint": make
      elementary: make
      # Red Hat family (RHEL, Fedora, CentOS, Rocky, Alma)
      RedHat: make
      Fedora: make
      CentOS: make
      Rocky: make
      AlmaLinux: make
      # Arch family
      Archlinux: make
      Manjaro: make
      # SUSE family
      openSUSE: make
      SLES: make
      # Alpine
      Alpine: make
    
    # Rolling release distributions (prefer native packages)
    rolling_distributions:
      - Archlinux
      - Manjaro
      - Fedora
      - openSUSE Tumbleweed
    
    # Stable distributions (prefer newer sources)
    stable_distributions:
      - Debian
      - Ubuntu
      - "Pop!_OS"
      - "Linux Mint"
      - elementary
      - RedHat
      - CentOS
      - Rocky
      - AlmaLinux
      - "Amazon Linux"
      - Alpine
      - SLES
      - "openSUSE Leap"
    
    # Ubuntu-based distributions that should use Ubuntu repositories
    ubuntu_derivatives:
      - Ubuntu
      - "Pop!_OS"
      - "Linux Mint"
      - elementary

  tasks:
    - name: Display detected OS information
      debug:
        msg: "Detected OS: {{ ansible_distribution }} {{ ansible_distribution_version }} ({{ ansible_os_family }})"

    - name: Determine if distribution is rolling or stable
      set_fact:
        is_rolling_distribution: "{{ ansible_distribution in rolling_distributions }}"
        is_stable_distribution: "{{ ansible_distribution in stable_distributions }}"

    - name: Display distribution type
      debug:
        msg: "Distribution type: {{ 'Rolling' if is_rolling_distribution else 'Stable' }}"

    # Enable backports repository for Debian stable releases
    - name: Enable backports repository (Debian)
      apt_repository:
        repo: "deb http://deb.debian.org/debian {{ ansible_distribution_release }}-backports main"
        state: present
        update_cache: yes
      when: ansible_os_family == "Debian" and ansible_distribution == "Debian" and is_stable_distribution
      ignore_errors: yes

    # Enable EPEL for RHEL family stable distributions
    - name: Enable EPEL repository (RHEL family)
      dnf:
        name: epel-release
        state: present
      when: ansible_os_family == "RedHat" and is_stable_distribution and ansible_distribution != "Fedora"
      ignore_errors: yes

    - name: Enable PowerTools/CRB repository for build dependencies (RHEL 8+)
      dnf:
        name: "{{ 'powertools' if ansible_distribution_major_version|int == 8 else 'crb' }}"
        state: present
        enablerepo: "{{ 'powertools' if ansible_distribution_major_version|int == 8 else 'crb' }}"
      when: ansible_os_family == "RedHat" and is_stable_distribution and ansible_distribution_major_version|int >= 8
      ignore_errors: yes

    - name: Ensure package cache is updated (Debian/Ubuntu)
      apt:
        update_cache: yes
        cache_valid_time: 3600
      when: ansible_os_family == "Debian"
      
    - name: Ensure package cache is updated (RHEL/Fedora)
      dnf:
        update_cache: yes
      when: ansible_os_family == "RedHat"
      ignore_errors: yes
      
    - name: Ensure package cache is updated (RHEL/CentOS with yum)
      yum:
        update_cache: yes
      when: ansible_os_family == "RedHat" and ansible_distribution_major_version|int < 8
      ignore_errors: yes
      
    - name: Ensure package cache is updated (Arch)
      pacman:
        update_cache: yes
      when: ansible_os_family == "Archlinux"
      
    - name: Ensure package cache is updated (SUSE)
      zypper:
        update_cache: yes
      when: ansible_os_family == "Suse"
      
    - name: Ensure package cache is updated (Alpine)
      apk:
        update_cache: yes
      when: ansible_os_family == "Alpine"
      
    - name: Check if make is already installed
      command: make --version
      register: make_version_check
      failed_when: false
      changed_when: false
      
    - name: Display current make version if installed
      debug:
        msg: "Make is already installed: {{ make_version_check.stdout | regex_replace('\\n.*', '') }}"
      when: make_version_check.rc == 0
      
    - name: Install/upgrade make from backports (Debian stable)
      apt:
        name: "{{ make_packages[ansible_distribution] | default('make') }}"
        state: latest
        default_release: "{{ ansible_distribution_release }}-backports"
      when: ansible_os_family == "Debian" and ansible_distribution == "Debian" and is_stable_distribution
      ignore_errors: yes
      
    - name: Install/upgrade make (Ubuntu and derivatives stable) 
      apt:
        name: "{{ make_packages[ansible_distribution] | default('make') }}"
        state: latest
      when: ansible_os_family == "Debian" and ansible_distribution in ubuntu_derivatives and is_stable_distribution
      
    - name: Install/upgrade make (Debian/Ubuntu rolling or fallback)
      apt:
        name: "{{ make_packages[ansible_distribution] | default('make') }}"
        state: latest
      when: ansible_os_family == "Debian" and (is_rolling_distribution or ansible_failed_result is defined)
      
    - name: Install/upgrade make (RHEL/Fedora/CentOS stable with EPEL)
      dnf:
        name: "{{ make_packages[ansible_distribution] | default('make') }}"
        state: latest
        enablerepo: epel
      when: ansible_os_family == "RedHat" and is_stable_distribution and ansible_distribution != "Fedora"
      ignore_errors: yes
      
    - name: Install/upgrade make (Fedora rolling)
      dnf:
        name: "{{ make_packages[ansible_distribution] | default('make') }}"
        state: latest
      when: ansible_os_family == "RedHat" and ansible_distribution == "Fedora"
      ignore_errors: yes
      
    - name: Install/upgrade make (RHEL/CentOS with yum fallback)
      yum:
        name: "{{ make_packages[ansible_distribution] | default('make') }}"
        state: latest
        enablerepo: epel
      when: ansible_os_family == "RedHat" and is_stable_distribution and ansible_distribution_major_version|int < 8
      ignore_errors: yes
      
    - name: Install/upgrade make (Arch Linux)
      pacman:
        name: "{{ make_packages[ansible_distribution] | default('make') }}"
        state: latest
      when: ansible_os_family == "Archlinux"
      
    - name: Install/upgrade make (SUSE)
      zypper:
        name: "{{ make_packages[ansible_distribution] | default('make') }}"
        state: latest
      when: ansible_os_family == "Suse"
      
    - name: Install/upgrade make (Alpine)
      apk:
        name: "{{ make_packages[ansible_distribution] | default('make') }}"
        state: latest
      when: ansible_os_family == "Alpine"
      
    - name: Verify make installation
      command: make --version
      register: make_final_version
      changed_when: false
      
    - name: Display final make version
      debug:
        msg: "Make installation complete: {{ make_final_version.stdout | regex_replace('\\n.*', '') }}"
        
    - name: Ensure make is in PATH
      shell: which make
      register: make_path
      changed_when: false
      
    - name: Display make binary location
      debug:
        msg: "Make binary location: {{ make_path.stdout }}"

  handlers:
    - name: refresh package cache
      package:
        update_cache: yes