---
# Git Installation Playbook
# Cross-distribution git installation with package name mapping
# Supports: Debian/Ubuntu, RHEL/Fedora/CentOS, Arch, SUSE, Alpine

- name: Install Git across distributions
  hosts: localhost
  connection: local
  gather_facts: yes
  become: yes
  
  vars:
    # Package name mappings for different distributions
    git_packages:
      # Debian family (Ubuntu, Debian, Pop!_OS, etc.)
      Debian: git
      Ubuntu: git
      # Red Hat family (RHEL, Fedora, CentOS, Rocky, Alma)
      RedHat: git
      Fedora: git
      CentOS: git
      Rocky: git
      AlmaLinux: git
      # Arch family
      Archlinux: git
      Manjaro: git
      # SUSE family
      openSUSE: git
      SLES: git
      # Alpine
      Alpine: git
    
    # Rolling release distributions (prefer native packages)
    rolling_distributions:
      - Archlinux
      - Manjaro
      - Fedora
      - openSUSE Tumbleweed
    
    # Stable distributions (prefer newer sources)
    stable_distributions:
      - Debian
      - Ubuntu
      - "Pop!_OS"
      - "Linux Mint"
      - elementary
      - RedHat
      - CentOS
      - Rocky
      - AlmaLinux
      - "Amazon Linux"
      - Alpine
      - SLES
      - "openSUSE Leap"
    
    # Ubuntu-based distributions that should use Ubuntu PPA
    ubuntu_derivatives:
      - Ubuntu
      - "Pop!_OS"
      - "Linux Mint"
      - elementary

  tasks:
    - name: Display detected OS information
      debug:
        msg: "Detected OS: {{ ansible_distribution }} {{ ansible_distribution_version }} ({{ ansible_os_family }})"

    - name: Determine if distribution is rolling or stable
      set_fact:
        is_rolling_distribution: "{{ ansible_distribution in rolling_distributions }}"
        is_stable_distribution: "{{ ansible_distribution in stable_distributions }}"

    - name: Display distribution type
      debug:
        msg: "Distribution type: {{ 'Rolling' if is_rolling_distribution else 'Stable' }}"

    # Add Git PPA for Ubuntu and Ubuntu derivatives to get newer versions
    - name: Add git-core PPA for newer git (Ubuntu and derivatives)
      apt_repository:
        repo: ppa:git-core/ppa
        state: present
        update_cache: yes
      when: ansible_os_family == "Debian" and ansible_distribution in ubuntu_derivatives and is_stable_distribution
      ignore_errors: yes

    # Add backports repository for Debian stable releases
    - name: Enable backports repository (Debian)
      apt_repository:
        repo: "deb http://deb.debian.org/debian {{ ansible_distribution_release }}-backports main"
        state: present
        update_cache: yes
      when: ansible_os_family == "Debian" and ansible_distribution == "Debian" and is_stable_distribution
      ignore_errors: yes

    # Add EPEL and newer git sources for RHEL family stable distributions
    - name: Enable EPEL repository (RHEL family)
      dnf:
        name: epel-release
        state: present
      when: ansible_os_family == "RedHat" and is_stable_distribution and ansible_distribution != "Fedora"
      ignore_errors: yes

    - name: Enable PowerTools/CRB repository for git dependencies (RHEL 8+)
      dnf:
        name: "{{ 'powertools' if ansible_distribution_major_version|int == 8 else 'crb' }}"
        state: present
        enablerepo: "{{ 'powertools' if ansible_distribution_major_version|int == 8 else 'crb' }}"
      when: ansible_os_family == "RedHat" and is_stable_distribution and ansible_distribution_major_version|int >= 8
      ignore_errors: yes

    - name: Ensure package cache is updated (Debian/Ubuntu)
      apt:
        update_cache: yes
        cache_valid_time: 3600
      when: ansible_os_family == "Debian"
      
    - name: Ensure package cache is updated (RHEL/Fedora)
      dnf:
        update_cache: yes
      when: ansible_os_family == "RedHat"
      ignore_errors: yes  # In case yum is used instead of dnf
      
    - name: Ensure package cache is updated (RHEL/CentOS with yum)
      yum:
        update_cache: yes
      when: ansible_os_family == "RedHat" and ansible_distribution_major_version|int < 8
      ignore_errors: yes
      
    - name: Ensure package cache is updated (Arch)
      pacman:
        update_cache: yes
      when: ansible_os_family == "Archlinux"
      
    - name: Ensure package cache is updated (SUSE)
      zypper:
        update_cache: yes
      when: ansible_os_family == "Suse"
      
    - name: Ensure package cache is updated (Alpine)
      apk:
        update_cache: yes
      when: ansible_os_family == "Alpine"
      
    - name: Check if git is already installed
      command: git --version
      register: git_version_check
      failed_when: false
      changed_when: false
      
    - name: Display current git version if installed
      debug:
        msg: "Git is already installed: {{ git_version_check.stdout }}"
      when: git_version_check.rc == 0
      
    - name: Install/upgrade git from backports (Debian stable)
      apt:
        name: "{{ git_packages[ansible_distribution] | default('git') }}"
        state: latest
        default_release: "{{ ansible_distribution_release }}-backports"
      when: ansible_os_family == "Debian" and ansible_distribution == "Debian" and is_stable_distribution
      ignore_errors: yes
      
    - name: Install/upgrade git from PPA (Ubuntu and derivatives stable) 
      apt:
        name: "{{ git_packages[ansible_distribution] | default('git') }}"
        state: latest
      when: ansible_os_family == "Debian" and ansible_distribution in ubuntu_derivatives and is_stable_distribution
      
    - name: Install/upgrade git (Debian/Ubuntu rolling or fallback)
      apt:
        name: "{{ git_packages[ansible_distribution] | default('git') }}"
        state: latest
      when: ansible_os_family == "Debian" and (is_rolling_distribution or ansible_failed_result is defined)
      
    - name: Install/upgrade git (RHEL/Fedora/CentOS stable with EPEL)
      dnf:
        name: "{{ git_packages[ansible_distribution] | default('git') }}"
        state: latest
        enablerepo: epel
      when: ansible_os_family == "RedHat" and is_stable_distribution and ansible_distribution != "Fedora"
      ignore_errors: yes
      
    - name: Install/upgrade git (Fedora rolling)
      dnf:
        name: "{{ git_packages[ansible_distribution] | default('git') }}"
        state: latest
      when: ansible_os_family == "RedHat" and ansible_distribution == "Fedora"
      ignore_errors: yes
      
    - name: Install/upgrade git (RHEL/CentOS with yum fallback)
      yum:
        name: "{{ git_packages[ansible_distribution] | default('git') }}"
        state: latest
        enablerepo: epel
      when: ansible_os_family == "RedHat" and is_stable_distribution and ansible_distribution_major_version|int < 8
      ignore_errors: yes
      
    - name: Install/upgrade git (Arch Linux)
      pacman:
        name: "{{ git_packages[ansible_distribution] | default('git') }}"
        state: latest
      when: ansible_os_family == "Archlinux"
      
    - name: Install/upgrade git (SUSE)
      zypper:
        name: "{{ git_packages[ansible_distribution] | default('git') }}"
        state: latest
      when: ansible_os_family == "Suse"
      
    - name: Install/upgrade git (Alpine)
      apk:
        name: "{{ git_packages[ansible_distribution] | default('git') }}"
        state: latest
      when: ansible_os_family == "Alpine"
      
    - name: Verify git installation
      command: git --version
      register: git_final_version
      changed_when: false
      
    - name: Display final git version
      debug:
        msg: "Git installation complete: {{ git_final_version.stdout }}"
        
    - name: Ensure git is in PATH
      shell: which git
      register: git_path
      changed_when: false
      
    - name: Display git binary location
      debug:
        msg: "Git binary location: {{ git_path.stdout }}"

  handlers:
    - name: refresh package cache
      package:
        update_cache: yes