---
# Wget Removal Playbook
# Cross-distribution wget package removal

- name: Remove wget across distributions
  hosts: localhost
  connection: local
  gather_facts: yes
  become: yes
  
  tasks:
    - name: Display detected OS information
      debug:
        msg: "Detected OS: {{ ansible_distribution }} {{ ansible_distribution_version }} ({{ ansible_os_family }})"

    - name: Check if wget is currently installed
      command: wget --version
      register: wget_version_check
      failed_when: false
      changed_when: false

    - name: Display current wget status
      debug:
        msg: "Wget is {{ 'currently installed' if wget_version_check.rc == 0 else 'not installed' }}"

    - name: Skip removal if wget is not installed
      debug:
        msg: "Wget is not installed, nothing to remove"
      when: wget_version_check.rc != 0

    - name: Remove wget (Debian/Ubuntu)
      apt:
        name: wget
        state: absent
        autoremove: yes
      when: ansible_os_family == "Debian" and wget_version_check.rc == 0

    - name: Remove wget (RedHat/Fedora)
      dnf:
        name: wget
        state: absent
      when: ansible_os_family == "RedHat" and wget_version_check.rc == 0

    - name: Remove wget (Arch Linux)
      pacman:
        name: wget
        state: absent
      when: ansible_os_family == "Archlinux" and wget_version_check.rc == 0

    - name: Remove wget (SUSE)
      zypper:
        name: wget
        state: absent
      when: ansible_os_family == "Suse" and wget_version_check.rc == 0

    - name: Remove wget (Alpine)
      apk:
        name: wget
        state: absent
      when: ansible_os_family == "Alpine" and wget_version_check.rc == 0

    - name: Verify wget removal
      command: wget --version
      register: wget_removal_check
      failed_when: false
      changed_when: false

    - name: Display removal success
      debug:
        msg: "Wget has been successfully removed from the system"
      when: wget_removal_check.rc != 0 and wget_version_check.rc == 0

    - name: Display removal warning if still present
      debug:
        msg: "Warning: Wget may still be present on the system"
      when: wget_removal_check.rc == 0

    - name: Display post-removal notes
      debug:
        msg:
          - "Wget removal complete!"
          - "Alternative download tools:"
          - "  - curl (install with: pactopus install curl)"
          - "  - Browser downloads"
          - "  - Package manager downloads"
      when: wget_removal_check.rc != 0 and wget_version_check.rc == 0