---
# Bat Installation Playbook
# Cross-distribution bat installation with package name mapping
# Handles bat vs batcat naming differences across distributions
# Supports: Debian/Ubuntu, RHEL/Fedora/CentOS, Arch, SUSE, Alpine

- name: Install Bat across distributions
  hosts: localhost
  connection: local
  gather_facts: yes
  become: yes
  
  vars:
    # Package name mappings for different distributions
    # Note: Debian/Ubuntu use 'batcat' due to existing 'bat' package conflict
    bat_packages:
      # Debian family (Ubuntu, Debian, Pop!_OS, etc.) - uses batcat
      Debian: batcat
      Ubuntu: batcat
      "Pop!_OS": batcat
      "Linux Mint": batcat
      elementary: batcat
      # Red Hat family (RHEL, Fedora, CentOS, Rocky, Alma) - uses bat
      RedHat: bat
      Fedora: bat
      CentOS: bat
      Rocky: bat
      AlmaLinux: bat
      # Arch family - uses bat
      Archlinux: bat
      Manjaro: bat
      # SUSE family - uses bat
      openSUSE: bat
      SLES: bat
      # Alpine - uses bat
      Alpine: bat
    
    # Binary name mappings (what the actual command is called)
    bat_binaries:
      # Debian family uses batcat binary
      Debian: batcat
      Ubuntu: batcat
      "Pop!_OS": batcat
      "Linux Mint": batcat
      elementary: batcat
      # All others use bat binary
      RedHat: bat
      Fedora: bat
      CentOS: bat
      Rocky: bat
      AlmaLinux: bat
      Archlinux: bat
      Manjaro: bat
      openSUSE: bat
      SLES: bat
      Alpine: bat
    
    # Rolling release distributions (prefer native packages)
    rolling_distributions:
      - Archlinux
      - Manjaro
      - Fedora
      - openSUSE Tumbleweed
    
    # Stable distributions (prefer newer sources)
    stable_distributions:
      - Debian
      - Ubuntu
      - "Pop!_OS"
      - "Linux Mint"
      - elementary
      - RedHat
      - CentOS
      - Rocky
      - AlmaLinux
      - "Amazon Linux"
      - Alpine
      - SLES
      - "openSUSE Leap"
    
    # Ubuntu-based distributions that should use Ubuntu repositories
    ubuntu_derivatives:
      - Ubuntu
      - "Pop!_OS"
      - "Linux Mint"
      - elementary

  tasks:
    - name: Display detected OS information
      debug:
        msg: "Detected OS: {{ ansible_distribution }} {{ ansible_distribution_version }} ({{ ansible_os_family }})"

    - name: Determine if distribution is rolling or stable
      set_fact:
        is_rolling_distribution: "{{ ansible_distribution in rolling_distributions }}"
        is_stable_distribution: "{{ ansible_distribution in stable_distributions }}"

    - name: Display distribution type
      debug:
        msg: "Distribution type: {{ 'Rolling' if is_rolling_distribution else 'Stable' }}"

    - name: Display package and binary names for this distribution
      debug:
        msg: 
          - "Package name: {{ bat_packages[ansible_distribution] | default('bat') }}"
          - "Binary name: {{ bat_binaries[ansible_distribution] | default('bat') }}"

    # Enable backports repository for Debian stable releases
    - name: Enable backports repository (Debian)
      apt_repository:
        repo: "deb http://deb.debian.org/debian {{ ansible_distribution_release }}-backports main"
        state: present
        update_cache: yes
      when: ansible_os_family == "Debian" and ansible_distribution == "Debian" and is_stable_distribution
      ignore_errors: yes

    # Enable EPEL for RHEL family stable distributions
    - name: Enable EPEL repository (RHEL family)
      dnf:
        name: epel-release
        state: present
      when: ansible_os_family == "RedHat" and is_stable_distribution and ansible_distribution != "Fedora"
      ignore_errors: yes

    - name: Ensure package cache is updated (Debian/Ubuntu)
      apt:
        update_cache: yes
        cache_valid_time: 3600
      when: ansible_os_family == "Debian"
      
    - name: Ensure package cache is updated (RHEL/Fedora)
      dnf:
        update_cache: yes
      when: ansible_os_family == "RedHat"
      ignore_errors: yes
      
    - name: Ensure package cache is updated (RHEL/CentOS with yum)
      yum:
        update_cache: yes
      when: ansible_os_family == "RedHat" and ansible_distribution_major_version|int < 8
      ignore_errors: yes
      
    - name: Ensure package cache is updated (Arch)
      pacman:
        update_cache: yes
      when: ansible_os_family == "Archlinux"
      
    - name: Ensure package cache is updated (SUSE)
      zypper:
        update_cache: yes
      when: ansible_os_family == "Suse"
      
    - name: Ensure package cache is updated (Alpine)
      apk:
        update_cache: yes
      when: ansible_os_family == "Alpine"
      
    - name: Check if bat is already installed
      command: "{{ bat_binaries[ansible_distribution] | default('bat') }} --version"
      register: bat_version_check
      failed_when: false
      changed_when: false
      
    - name: Display current bat version if installed
      debug:
        msg: "Bat is already installed: {{ bat_version_check.stdout | regex_replace('\\n.*', '') }}"
      when: bat_version_check.rc == 0
      
    - name: Install/upgrade bat from backports (Debian stable)
      apt:
        name: "{{ bat_packages[ansible_distribution] | default('bat') }}"
        state: latest
        default_release: "{{ ansible_distribution_release }}-backports"
      when: ansible_os_family == "Debian" and ansible_distribution == "Debian" and is_stable_distribution
      ignore_errors: yes
      
    - name: Install/upgrade bat (Ubuntu and derivatives stable) 
      apt:
        name: "{{ bat_packages[ansible_distribution] | default('bat') }}"
        state: latest
      when: ansible_os_family == "Debian" and ansible_distribution in ubuntu_derivatives and is_stable_distribution
      
    - name: Install/upgrade bat (Debian/Ubuntu rolling or fallback)
      apt:
        name: "{{ bat_packages[ansible_distribution] | default('bat') }}"
        state: latest
      when: ansible_os_family == "Debian" and (is_rolling_distribution or ansible_failed_result is defined)
      
    - name: Install/upgrade bat (RHEL/Fedora/CentOS stable with EPEL)
      dnf:
        name: "{{ bat_packages[ansible_distribution] | default('bat') }}"
        state: latest
        enablerepo: epel
      when: ansible_os_family == "RedHat" and is_stable_distribution and ansible_distribution != "Fedora"
      ignore_errors: yes
      
    - name: Install/upgrade bat (Fedora rolling)
      dnf:
        name: "{{ bat_packages[ansible_distribution] | default('bat') }}"
        state: latest
      when: ansible_os_family == "RedHat" and ansible_distribution == "Fedora"
      ignore_errors: yes
      
    - name: Install/upgrade bat (RHEL/CentOS with yum fallback)
      yum:
        name: "{{ bat_packages[ansible_distribution] | default('bat') }}"
        state: latest
        enablerepo: epel
      when: ansible_os_family == "RedHat" and is_stable_distribution and ansible_distribution_major_version|int < 8
      ignore_errors: yes
      
    - name: Install/upgrade bat (Arch Linux)
      pacman:
        name: "{{ bat_packages[ansible_distribution] | default('bat') }}"
        state: latest
      when: ansible_os_family == "Archlinux"
      
    - name: Install/upgrade bat (SUSE)
      zypper:
        name: "{{ bat_packages[ansible_distribution] | default('bat') }}"
        state: latest
      when: ansible_os_family == "Suse"
      
    - name: Install/upgrade bat (Alpine)
      apk:
        name: "{{ bat_packages[ansible_distribution] | default('bat') }}"
        state: latest
      when: ansible_os_family == "Alpine"
      
    - name: Verify bat installation
      command: "{{ bat_binaries[ansible_distribution] | default('bat') }} --version"
      register: bat_final_version
      changed_when: false
      
    - name: Display final bat version
      debug:
        msg: "Bat installation complete: {{ bat_final_version.stdout | regex_replace('\\n.*', '') }}"
        
    - name: Ensure bat is in PATH
      shell: "which {{ bat_binaries[ansible_distribution] | default('bat') }}"
      register: bat_path
      changed_when: false
      
    - name: Display bat binary location
      debug:
        msg: "Bat binary location: {{ bat_path.stdout }}"

    - name: Check for bat alias setup (Debian/Ubuntu using batcat)
      stat:
        path: /usr/bin/bat
      register: bat_alias_check
      when: ansible_os_family == "Debian"

    - name: Display bat alias information (Debian/Ubuntu)
      debug:
        msg: 
          - "Note: On Debian/Ubuntu, bat is installed as 'batcat' due to package naming conflicts"
          - "Binary location: {{ bat_path.stdout }}"
          - "You can create an alias: alias bat='batcat'"
          - "Or use the full command: batcat"
      when: ansible_os_family == "Debian"

    - name: Display bat usage hint
      debug:
        msg: 
          - "Bat installation complete!"
          - "Usage: {{ bat_binaries[ansible_distribution] | default('bat') }} filename    # View file with syntax highlighting"
          - "       {{ bat_binaries[ansible_distribution] | default('bat') }} --help      # Show all options"
          - "       {{ bat_binaries[ansible_distribution] | default('bat') }} --list-themes  # List available themes"

  handlers:
    - name: refresh package cache
      package:
        update_cache: yes